### GET request to example server
GET http://localhost:8080

###

GET http://localhost:8080/api/v1software-engineers

###

GET http://localhost:8080/api/v1software-engineers

###

POST http://localhost:8080/api/v1software-engineers
Content-Type: application/json

{
  "name": "Sam",
  "techStack": "manager, sales, dgm"
}

###

DELETE http://localhost:8080/api/v1software-engineers/1

###

PATCH http://localhost:8080/api/v1software-engineers/2
Content-Type: application/json

{
  "name": "Alice Johnson"
}